### ISSUE TITLE
Using built-artifacts instead of wrapper scripts

### ISSUE THREAD

**Issue by bedbad** [FabianHahn/bazel-zig-cc#1]
Instead of using wrapper scripts of zig binary for tool_paths like here or building them as zig targets as in [launcher.zig](https://git.sr.ht/~motiejus/bazel-zig-cc/tree/main/item/toolchain/launcher.zig), it's [possible now](https://github.com/bazelbuild/bazel/issues/7746) to use built-artifacts for tools. Maybe write them in Starlark?

**Comment by FabianHahn** [comment]
Apologies for the late response. This is my personal development fork of bazel-zig-cc that I only use infrequently. You can find the upstream repo of the project at SourceHut [here](https://git.sr.ht/~motiejus/bazel-zig-cc). There is also a mailing list at [~motiejus/bazel-zig-cc@lists.sr.ht](https://lists.sr.ht/~motiejus/bazel-zig-cc) to suggest and discuss new features with all the developers. The's talk about the project moving to GitHub soon, which I personally agree would be nice, but for now SourceHut is where it lives.
